[workspace]
members = [
  "crates/app-demo-core",
  "crates/app-demo-adapter-fastly",
  "crates/app-demo-adapter-cloudflare",
  "crates/app-demo-adapter-axum",
]
resolver = "2"

[workspace.dependencies]
anyedge-adapter-cloudflare = { path = "../../crates/anyedge-adapter-cloudflare" }
anyedge-adapter-fastly = { path = "../../crates/anyedge-adapter-fastly" }
anyedge-adapter-axum = { path = "../../crates/anyedge-adapter-axum" }
anyedge-core = { path = "../../crates/anyedge-core" }
app-demo-core = { path = "crates/app-demo-core" }
anyhow = "1"
axum = "0.7"
bytes = "1"
fastly = "0.11"
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }
log = "0.4"
once_cell = "1"
simple_logger = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
worker = { version = "0.6", default-features = false, features = ["http"] }
