[workspace]
members = [
  "crates/app-demo-core",
  "crates/app-demo-adapter-axum",
  "crates/app-demo-adapter-cloudflare",
  "crates/app-demo-adapter-fastly",
  "crates/app-demo-adapter-spin",
]
resolver = "2"

[workspace.package]
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.8"
bytes = "1"
edgezero-adapter-axum = { path = "../../crates/edgezero-adapter-axum" }
edgezero-adapter-cloudflare = { path = "../../crates/edgezero-adapter-cloudflare" }
edgezero-adapter-fastly = { path = "../../crates/edgezero-adapter-fastly" }
edgezero-adapter-spin = { path = "../../crates/edgezero-adapter-spin" }
edgezero-core = { path = "../../crates/edgezero-core" }
spin-sdk = { version = "5.2", default-features = false }
fastly = "0.11"
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }
log = "0.4"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simple_logger = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
worker = { version = "0.7", default-features = false, features = ["http"] }

[profile.release]
debug = 1
codegen-units = 1
lto = "fat"
