[workspace]
members = [
  "crates/app-demo-core",
  "crates/app-demo-adapter-fastly",
  "crates/app-demo-adapter-cloudflare",
]
resolver = "2"

[workspace.dependencies]
anyedge-adapter-cloudflare = { path = "../../crates/anyedge-adapter-cloudflare" }
anyedge-adapter-fastly = { path = "../../crates/anyedge-adapter-fastly" }
anyedge-core = { path = "../../crates/anyedge-core" }
app-demo-core = { path = "crates/app-demo-core" }
fastly = "0.11"
bytes = "1"
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }
serde = { version = "1", features = ["derive"] }
worker = { version = "0.6", default-features = false, features = ["http"] }
log = "0.4"
