[workspace]
members = [
    "crates/anyedge-adapter-cloudflare",
    "crates/anyedge-adapter-fastly",
    "crates/anyedge-cli",
    "crates/anyedge-core",
    "crates/anyedge-macros",
    "examples/app-demo/crates/app-demo-adapter-cloudflare",
    "examples/app-demo/crates/app-demo-core",
    "examples/app-demo/crates/app-demo-adapter-fastly",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["AnyEdge Team <dev@anyedge.dev>"]
license = "Apache-2.0"

[workspace.dependencies]
anyedge-adapter-cloudflare = { path = "crates/anyedge-adapter-cloudflare", default-features = false }
anyedge-adapter-fastly = { path = "crates/anyedge-adapter-fastly", default-features = false }
anyedge-core = { path = "crates/anyedge-core", default-features = false }
anyhow = "1"
app-demo-core = { path = "examples/app-demo/crates/app-demo-core" }
async-compression = { version = "0.4", features = ["futures-io", "gzip", "brotli"] }
async-stream = "0.3"
async-trait = "0.1"
brotli = "3"
bytes = "1"
chrono = "0.4"
fastly = "0.11"
fern = "0.6"
flate2 = { version = "1", features = ["rust_backend"] }
futures = { version = "0.3", features = ["std", "executor"] }
futures-util = { version = "0.3", features = ["alloc", "io"] }
handlebars = "6"
http = "1"
http-body = "1"
log = "0.4"
log-fastly = "0.11"
matchit = "0.8"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
simple_logger = "4"
tempfile = "3"
thiserror = "2"
toml = { version = "0.9" }
tower = { version = "0.4", features = ["util"] }
tower-layer = "0.3"
tower-service = "0.3"
tracing = "0.1"
validator = { version = "0.20", features = ["derive"] }
walkdir = { version = "2" }
worker = { version = "0.6", features = ["http"] }
