[workspace]
members = [
    "crates/edgezero-adapter-axum",
    "crates/edgezero-adapter-cloudflare",
    "crates/edgezero-adapter-fastly",
    "crates/edgezero-adapter",
    "crates/edgezero-cli",
    "crates/edgezero-core",
    "crates/edgezero-macros",
    "examples/app-demo/crates/app-demo-adapter-cloudflare",
    "examples/app-demo/crates/app-demo-adapter-axum",
    "examples/app-demo/crates/app-demo-core",
    "examples/app-demo/crates/app-demo-adapter-fastly",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["EdgeZero Team <dev@edgezero.dev>"]
license = "Apache-2.0"

[workspace.dependencies]
anyhow = "1"
app-demo-core = { path = "examples/app-demo/crates/app-demo-core" }
async-compression = { version = "0.4", features = ["futures-io", "gzip", "brotli"] }
async-stream = "0.3"
async-trait = "0.1"
axum = { version = "0.8", default-features = true }
brotli = "8"
bytes = "1"
chrono = "0.4"
ctor = "0.6"
edgezero-adapter = { path = "crates/edgezero-adapter" }
edgezero-adapter-axum = { path = "crates/edgezero-adapter-axum", default-features = false }
edgezero-adapter-cloudflare = { path = "crates/edgezero-adapter-cloudflare", default-features = false }
edgezero-adapter-fastly = { path = "crates/edgezero-adapter-fastly", default-features = false }
edgezero-core = { path = "crates/edgezero-core", default-features = false }
fastly = "0.11"
fern = "0.7"
flate2 = { version = "1", features = ["rust_backend"] }
futures = { version = "0.3", features = ["std", "executor"] }
futures-util = { version = "0.3", features = ["alloc", "io"] }
handlebars = "6"
http = "1"
http-body = "1"
log = "0.4"
log-fastly = "0.11"
matchit = "0.9"
once_cell = "1"
reqwest = { version = "0.13", default-features = false, features = ["rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
simple_logger = "5"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
toml = { version = "0.9" }
tower = { version = "0.5", features = ["util"] }
tower-layer = "0.3"
tower-service = "0.3"
tracing = "0.1"
validator = { version = "0.20", features = ["derive"] }
walkdir = { version = "2" }
worker = { version = "0.6", features = ["http"] }
