[build]
target = "wasm32-wasip1"

[target.'cfg(target_arch = "wasm32")']
# Use Viceroy to run wasm built from binaries in this crate or dependents.
# Points to the demo service config by default.
runner = "wasmtime run --dir=. -- "
