[package]
name = "anyedge-app-lib"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "anyedge_app_lib"
path = "src/lib.rs"

[dependencies]
anyedge-core = { path = "../../crates/anyedge-core" }

