[package]
name = "app-demo-adapter-fastly"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "app-demo-adapter-fastly"
path = "src/main.rs"

[features]
default = []
fastly = ["anyedge-adapter-fastly/fastly"]

[dependencies]
app-demo-core = { workspace = true }
anyedge-adapter-fastly = { workspace = true }
log = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
anyedge-core = { workspace = true }
anyedge-adapter-fastly = { workspace = true, features = ["fastly"] }
fastly = { workspace = true }
once_cell = { workspace = true }
